version: '3'

services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=nice_pass
      - PGDATA=/var/lib/postgresql/data/watcher/
    volumes:
      - /opt/starter/psql/watcher:/var/lib/postgresql/data/watcher/

#    hostname: rabbit
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#  worker:
#    build: .
#    command: celery -A twitter_site worker -l info
#    volumes:
#      - .:/code
#    environment:
#      - RABBITMQ_HOSTNAME=rabbit
#    links:
#      - rabbit
#    depends_on:
#      - rabbit
