# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 22:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchedElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('html_element', models.CharField(max_length=200)),
                ('element_value', models.TextField(blank=True, null=True)),
                ('check_interval_days', models.IntegerField(default=1, help_text='The interval to check html element in days.')),
                ('cur_task_id', models.CharField(blank=True, max_length=36, null=True)),
                ('callback_url', models.URLField()),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time the html element was checked for changes.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
