# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcher', '0002_auto_20170914_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedelement',
            name='check_interval_hours',
            field=models.FloatField(default=1.0, help_text='The interval to check html element in days.'),
        ),
    ]
